import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Gusto',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: '/images/brand/gusto-small.svg',
                media: '(prefers-color-scheme: light)',
            },
            { url: '/images/brand/gusto-small-negative.svg', media: '(prefers-color-scheme: dark)' },
        ],
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                {children}
            </body>
        </html>
    )
}
