import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/AuthContext'

import PaymentVerification from '@/components/PaymentVerification'

import { ToastProvider } from '@/context/ToastContext'


const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ['latin'],
    variable: '--font-plus',
})

const gliker = localFont({
    src: [
        {
            path: '../public/fonts/Gliker/Gliker-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
})

export const metadata: Metadata = {
    title: 'Gusto',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: '/images/brand/gusto-small.svg',
                media: '(prefers-color-scheme: light)',
            },
            {
                url: '/images/brand/gusto-small-negative.svg',
                media: '(prefers-color-scheme: dark)',
            },
        ],
    },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="es" data-scroll-behavior="smooth">
            <body
                className={`${plusJakartaSans.className} ${gliker.className}`}
            >
                <ToastProvider>
                    <AuthProvider>
                        <PaymentVerification />
                        {children}
                    </AuthProvider>
                </ToastProvider>
            </body>
        </html>
    )
}
